### ISSUE TITLE
Hey Buddy,

### ISSUE THREAD

**Issue by E343IO** [norepository/wifi-grabber-rubberducky#2]
> They are quite more complicated but imma have a look, if ill find out something imma post, make sure to follow me! 😉

Hey buddy, 
I see ur review of shark tool i have added 3 more in it but they didn't merged my pull ... u can see my pull on https://github.com/Bhaviktutorials/shark/pull/33
I had closed it ... 
If u wanna some help then let me know.

_Originally posted by @tech2gamer in https://github.com/norepository/wifi-grabber-rubberducky/issues/1#issuecomment-917485715_

**Comment by norepository** [comment]
Kinda new to this so if you have any idea for new versions or new rubber ducky script add me as a friend on discord (tony#5678) and we can have a look

**Comment by tech2gamer** [comment]
> Kinda new to this so if you have any idea for new versions or new rubber ducky script add me as a friend on discord (tony#5678) and we can have a look

Hey buddy, 
the username tony#5678 have already requested to be a friend on discord please crosscheck it.
Thanking you 
Mr.Elloit

**Comment by E343IO** [comment]
> Kinda new to this so if you have any idea for new versions or new rubber ducky script add me as a friend on discord (tony#5678) and we can have a look

Hey buddy,
the username tony#5678 have already requested to be a friend on discord please crosscheck it.
Thanking you
Mr.Derek

**Comment by norepository** [comment]
Accepted! :-)
