### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by TobeCounted** [norepository/wifi-grabber-rubberducky#7]
Hey there,
First of all I appreciate your time for writing this script and your time for answering.
so the question is :
STRING $SMTPInfo.Credentials = New-Object System.Net.NetworkCredential('SENDER-EMAIL', 'SENDER-PASSWORD')
Should I write the email and the email pass with or without the ' ' (example : (example@gmail.com) or ('example@gmail.com')
and the comma ('SENDER-EMAIL', 'SENDER-PASSWORD') between the email and password are necessary?

Thank you very much and sorry if I was worng by opening this ticket.

**Comment by nthacker69** [comment]
Yeah I'm not to sure either. I tried the chrome password stealer and still waiting for a reply about that. If I get a reply I'll tell you.

**Comment by norepository** [comment]
Hey, the email and password format should be something like this: (‘qwerty@qwerty.com’, ’qwerty1234’)
Recently Google did some changes about allowing “not secure apps” so it might not work!
Have a good one!
