### ISSUE TITLE
Email did not come through.

### ISSUE THREAD

**Issue by nthacker69** [norepository/wifi-grabber-rubberducky#8]
I replaced the email and password (left the speech marks in) plugged it in, it did some stuff and then I check my emails several times but still nothing comes through. Please could someone help me with this. It seems to be happening with every one of the payloads that require an email address and password.

**Comment by norepository** [comment]
Hey, check this out: https://support.google.com/accounts/answer/6010255?hl=en
Seems that Google made some changes and not allowing login just with email and password anymore

**Comment by JakeAndre** [comment]
Whats the alternative for google gmail ? Have anyone try it using microsoft mail?

**Comment by norepository** [comment]
Hey, i haven’t touched this after google fix so i dont know if there is an alternative. If you find something feel free to post it down below :-)

**Comment by its0Cream** [comment]
You could prob. use outlook, maybe?

**Comment by its0Cream** [comment]
> Hey, i haven’t touched this after google fix so i dont know if there is an alternative. If you find something feel free to post it down below :-)

Im trying to use microsoft outlook, but im no pro at this, but ik that is probably possible!

**Comment by norepository** [comment]
Hey, ive just updated the script and now its fully working!
I replaced Gmail SMTP with Outlook's, it should work all again.
Let me know if you have any other problem.
